/**************************************************************************************************************************************
 * Insercion de datos semilla en la tabla SEGT_APLICACIONES
 **************************************************************************************************************************************/
INSERT INTO SEGT_APLICACIONES(COD_APLICACION,NOMBRE,DESCRIPCION)
VALUES('ORION','OrionSecurity','Plataforma  de Gestion Centralizada de Modelo de Autenticaion y Autorizacion de Usuarios');
INSERT INTO SEGT_APLICACIONES(COD_APLICACION,NOMBRE,DESCRIPCION)
VALUES('GESTPYMESOC','GestPymeSOC','Plataforma  de Gestion para Pequenas y Medianas empresas dedicadas a Servicios de Obra Civil y Similares');
INSERT INTO SEGT_APLICACIONES(COD_APLICACION,NOMBRE,DESCRIPCION)
VALUES('MASTERCENTRAL','MasterCentral','Plataforma  de Gestion para el modela de datos de Maestras y tablas comunes');

/**************************************************************************************************************************************
 * Insercion de datos semilla en la tabla SEGT_ROLES
 **************************************************************************************************************************************/
INSERT INTO SEGT_ROLES(ID_APLICACION,NOMBRE,DESCRIPCION) VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION' ),'SUPERADMIN','ROL ESPECIAL RESERVADO POR LA APLICACION PARA ASIGNAR AL USUARIO QUE TIENE ACCESO SIN RESTRICCIONES A TODAS LAS OPCIONES');
INSERT INTO SEGT_ROLES(ID_APLICACION,NOMBRE,DESCRIPCION) VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION' ),'CLIENT_APPLICATION','ROL ESPECIAL RESERVADO PARA CONCEDER ACCESO A LAS DIFERENTES APLICACIONES CLIENTES DE ORION');
INSERT INTO SEGT_ROLES(ID_APLICACION,NOMBRE,DESCRIPCION) VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC' ),'SUPERADMIN','ROL ESPECIAL RESERVADO POR LA APLICACION PARA ASIGNAR AL USUARIO QUE TIENE ACCESO SIN RESTRICCIONES A TODAS LAS OPCIONES');
INSERT INTO SEGT_ROLES(ID_APLICACION,NOMBRE,DESCRIPCION) VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL' ),'SUPERADMIN','ROL ESPECIAL RESERVADO POR LA APLICACION PARA ASIGNAR AL USUARIO QUE TIENE ACCESO SIN RESTRICCIONES A TODAS LAS OPCIONES');

/**************************************************************************************************************************************
 * Insercion de datos semilla en la tabla SEGT_USUARIOS
 **************************************************************************************************************************************/
INSERT INTO SEGT_USUARIOS(LOGIN_ALIAS,PASSWORD,PASSWORD_SALT,NUM_IDENTIFICACION,
NOMBRE_COMPLETO,FEC_ULTIMO_INGRESO,IP_ULTIMO_INGRESO,COD_ISO_IDIOMA,
REINTENTOS_FALLIDOS,ES_BLOQUEADO_REINTENTOS,FEC_BLOQUEO,ES_ACTIVO)
VALUES('superadmin','ae454a608ba2bbcea43da001c640633a0ce14fc672de35b1c409f9a2164688f6','53d3eb556755fc2642d3659195c3b1c9','1047386637',
'ALEXANDER CASTRO OLIVO',NULL,NULL,'es',
NULL,'N',NULL,'S');

INSERT INTO SEGT_USUARIOS(LOGIN_ALIAS,PASSWORD,PASSWORD_SALT,NUM_IDENTIFICACION,
NOMBRE_COMPLETO,FEC_ULTIMO_INGRESO,IP_ULTIMO_INGRESO,COD_ISO_IDIOMA,
REINTENTOS_FALLIDOS,ES_BLOQUEADO_REINTENTOS,FEC_BLOQUEO,ES_ACTIVO)
VALUES('gestpymesoc','ae454a608ba2bbcea43da001c640633a0ce14fc672de35b1c409f9a2164688f6','53d3eb556755fc2642d3659195c3b1c9',NULL,
'GESTPYMESOC (APLICACION CLIENTE)',NULL,NULL,'es',
NULL,'N',NULL,'S');

INSERT INTO SEGT_USUARIOS(LOGIN_ALIAS,PASSWORD,PASSWORD_SALT,NUM_IDENTIFICACION,
NOMBRE_COMPLETO,FEC_ULTIMO_INGRESO,IP_ULTIMO_INGRESO,COD_ISO_IDIOMA,
REINTENTOS_FALLIDOS,ES_BLOQUEADO_REINTENTOS,FEC_BLOQUEO,ES_ACTIVO)
VALUES('mastercentral','ae454a608ba2bbcea43da001c640633a0ce14fc672de35b1c409f9a2164688f6','53d3eb556755fc2642d3659195c3b1c9',NULL,
'MASTERCENTRAL (APLICACION CLIENTE)',NULL,NULL,'es',
NULL,'N',NULL,'S');

/**************************************************************************************************************************************
 * Insercion de datos semilla en la tabla SEGT_ROLES_X_USUARIO
 **************************************************************************************************************************************/
INSERT INTO SEGT_ROLES_X_USUARIO(ID_USUARIO,ID_ROL) VALUES((SELECT ID_USUARIO FROM SEGT_USUARIOS WHERE LOGIN_ALIAS='superadmin'),(SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')));
INSERT INTO SEGT_ROLES_X_USUARIO(ID_USUARIO,ID_ROL) VALUES((SELECT ID_USUARIO FROM SEGT_USUARIOS WHERE LOGIN_ALIAS='gestpymesoc'),(SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='CLIENT_APPLICATION' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')));
INSERT INTO SEGT_ROLES_X_USUARIO(ID_USUARIO,ID_ROL) VALUES((SELECT ID_USUARIO FROM SEGT_USUARIOS WHERE LOGIN_ALIAS='superadmin'),(SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC')));
INSERT INTO SEGT_ROLES_X_USUARIO(ID_USUARIO,ID_ROL) VALUES((SELECT ID_USUARIO FROM SEGT_USUARIOS WHERE LOGIN_ALIAS='mastercentral'),(SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='CLIENT_APPLICATION' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')));
INSERT INTO SEGT_ROLES_X_USUARIO(ID_USUARIO,ID_ROL) VALUES((SELECT ID_USUARIO FROM SEGT_USUARIOS WHERE LOGIN_ALIAS='superadmin'),(SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')));

INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION'),NULL,'/services/security/usercredentials','Busqueda de Credenciales Por Login', 'Busqueda de credenciales para un login especifico desde cualquier aplicacion cliente');

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO)
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='CLIENT_APPLICATION' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/services/security/usercredentials' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')));
		
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION'),NULL,'/services/security/saveauthentication','Registrar Autenticacion', 'Registro de bitacora de autenticacion de un usuario dentro de una aplicacion cliente');

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO)
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='CLIENT_APPLICATION' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/services/security/saveauthentication' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')));
		
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION'),NULL,'/services/security/invalidatesession','Invalidar Sesion', 'Invalida la informacion de autenticacion para un usuario dentro de una aplicacion cliente');

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO)
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='CLIENT_APPLICATION' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/services/security/invalidatesession' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')));
		
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION'),NULL,'/services/security/accesstokenvalidity','Validar Vigencia de Token de Acceso', 'Valida la vigencia de un token de acceso para dar un mecanismo mas de seguridad');

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO)
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='CLIENT_APPLICATION' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/services/security/accesstokenvalidity' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')));
		
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION'),NULL,'/services/security/userroles','Obtener Roles x Usuario', 'Devuelve los roles para un usuario especifico dentro de una aplicacion cliente');

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO)
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='CLIENT_APPLICATION' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/services/security/userroles' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')));
		
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION'),NULL,'/services/security/roleresources','Obtener recursos/permisoss por rol', 'Devuelve los recursos/permisos de un rol para una aplicacion cliente');

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO)
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='CLIENT_APPLICATION' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/services/security/roleresources' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')));

INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION'),NULL,'/_masterentity/Application','Administracion de Aplicaciones', 'Administracion de Aplicaciones');

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO)
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/_masterentity/Application' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')));

INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION'),NULL,'/_masterentity/Role','Administracion de Roles', 'Administracion de Roles');

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO)
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/_masterentity/Role' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')));

INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION'),NULL,'/admin/user','Administracion de Usuarios', 'Administracion de Usuarios');

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO)
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/admin/user' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')));

INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION'),NULL,'/admin/modules','Administracion de Modulos', 'Administracion de Modulos');

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO)
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/admin/modules' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')));
		
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION'),NULL,'/admin/resources','Administracion de Recursos', 'Administracion de Recursos');

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO)
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/admin/resources' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')));
		
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION'),NULL,'/admin/rolesByResource','Autorizacion de Roles x recurso', 'Autorizacionde Roles x Recurso');

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO)
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/admin/rolesByResource' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'ORION')));

/**********************************************************************************************************************************************
 * Modulos y Recursos de MASTERCENTRAL
 **********************************************************************************************************************************************/

INSERT INTO SEGT_MODULOS(ID_APLICACION,NOMBRE,DESCRIPCION) VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'), 'General','General');
INSERT INTO SEGT_MODULOS(ID_APLICACION,NOMBRE,DESCRIPCION) VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'), 'Administracion Regional','Administracion Regional');
INSERT INTO SEGT_MODULOS(ID_APLICACION,NOMBRE,DESCRIPCION) VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'), 'Adminisracion Entidades','Adminisracion Entidades');
INSERT INTO SEGT_MODULOS(ID_APLICACION,NOMBRE,DESCRIPCION) VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'), 'Administracion Tributaria','Administracion Tributaria');
INSERT INTO SEGT_MODULOS(ID_APLICACION,NOMBRE,DESCRIPCION) VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'), 'Administracion Sistema','Administracion Sistema');


INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'General' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),'/_masterentity/IdentificationType','Tipos de Identificacion', 'Tipos de Identificacion');
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'General' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),'/admin/businessGroup','Grupos Empresariales', 'Grupos Empresariales');
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'General' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),'/admin/company','Empresas', 'Empresas');
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'General' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),'/admin/thirdPerson','Terceros', 'Terceros');

INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'Administracion Regional' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),'/_masterentity/Country','Paises', 'Paises');
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'Administracion Regional' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),'/_masterentity/Province','Departamentos', 'Departamentos');
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'Administracion Regional' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),'/_masterentity/City','Ciudades', 'Ciudades');

INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'Adminisracion Entidades' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),'/_masterentity/Bank','Bancos', 'Bancos');
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'Adminisracion Entidades' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),'/_masterentity/HealthAdminCompany','Administradoras de Salud (EPS)', 'Administradoras de Salud (EPS)');
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'Adminisracion Entidades' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),'/_masterentity/OccupationalRiskAdminCompany','Administradoras de Riesgo (ARL)', 'Administradoras de Riesgo (ARL)');
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'Adminisracion Entidades' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),'/_masterentity/PensionFundAdminCompany','Administradoras de Fodos de Pension (AFP)', 'Administradoras de Fodos de Pension (AFP)');
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'Adminisracion Entidades' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),'/_masterentity/CompensationFundAdminCompany','Cajas de Compensacion', 'Cajas de Compensacion');

INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'Administracion Tributaria' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),'/_masterentity/EconomicActivityTariffGrouping','Rubros Economicos', 'Rubros Economicos');
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'Administracion Tributaria' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),'/_masterentity/EconomicActivity','Actividades economicas', 'Actividades economicas');
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'Administracion Tributaria' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),'/_masterentity/TaxpayerType','Clasificacion tributaria', 'Clasificacion tributaria');
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'Administracion Tributaria' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),'/_masterentity/PaymentConcept','Conceptos de Pago', 'Conceptos de Pago');
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'Administracion Tributaria' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),'/_masterentity/RetentionConfig','Configuracion tarifas de Retencion', 'Configuracion tarifas de Retencion');

INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'Administracion Sistema' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),'/_masterentity/StateGrouping','Agrupadores de Estados', 'Agrupadores de Estados');
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'Administracion Sistema' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),'/_masterentity/State','Estados', 'Estados');
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'Administracion Sistema' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),'/_masterentity/ConfigParameter','Parametros de Configuracion', 'Parametros de Configuracion');
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'Administracion Sistema' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),'/_masterentity/Master','Maestros', 'Maestros');
INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'Administracion Sistema' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),'/_masterentity/MasterData','Valores de Maestros', 'Valores de Maestros');

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/_masterentity/IdentificationType' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/admin/businessGroup' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/admin/company' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/admin/thirdPerson' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/_masterentity/Country' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/_masterentity/Province' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/_masterentity/City' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/_masterentity/Bank' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/_masterentity/HealthAdminCompany' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/_masterentity/OccupationalRiskAdminCompany' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/_masterentity/PensionFundAdminCompany' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/_masterentity/CompensationFundAdminCompany' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/_masterentity/EconomicActivityTariffGrouping' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/_masterentity/EconomicActivity' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/_masterentity/TaxpayerType' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/_masterentity/PaymentConcept' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/_masterentity/RetentionConfig' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/_masterentity/StateGrouping' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/_masterentity/State' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/_masterentity/ConfigParameter' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/_masterentity/Master' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/_masterentity/MasterData' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'MASTERCENTRAL')));


/**********************************************************************************************************************************************
 * Modulos y Recursos de GESTPYMESOC
 **********************************************************************************************************************************************/
INSERT INTO SEGT_MODULOS(ID_APLICACION,NOMBRE,DESCRIPCION) VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC'), 'General','General');
INSERT INTO SEGT_MODULOS(ID_APLICACION,NOMBRE,DESCRIPCION) VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC'), 'Terceros','Terceros');
INSERT INTO SEGT_MODULOS(ID_APLICACION,NOMBRE,DESCRIPCION) VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC'), 'Nomina','Nomina');

INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'General' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC')),'/_masterentity/Appointment','Cargos Laborales', 'Cargos Laborales');

INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'General' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC')),'/_masterentity/ContractTerminationReason','Motivos terminacion contrato', 'Motivos terminacion contrato');

INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'Terceros' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC')),'/admin/thirdPerson/provider','Proveedores', 'Proveedores');

INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'Terceros' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC')),'/admin/thirdPerson/customer','Clientes', 'Clientes');

INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'Terceros' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC')),'/admin/thirdPerson/employee','Empleados', 'Empleados');

INSERT INTO SEGT_RECURSOS(ID_APLICACION,ID_MODULO,RUTA_RECURSO,NOMBRE,DESCRIPCION)
VALUES((SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC'),(SELECT ID_MODULO FROM SEGT_MODULOS WHERE NOMBRE = 'Nomina' AND ID_MODULO_PADRE IS NULL AND ID_APLICACION = (SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC')),'/payroll/employmentContract','Contratos Laborales', 'Contratos Laborales');

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/_masterentity/Appointment' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/_masterentity/ContractTerminationReason' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/admin/thirdPerson/provider' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/admin/thirdPerson/customer' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/admin/thirdPerson/employee' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC')));

INSERT INTO SEGT_RECURSOS_X_ROLES(ID_ROL,ID_RECURSO) 
VALUES((SELECT ID_ROL FROM SEGT_ROLES WHERE NOMBRE='SUPERADMIN' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC')),
(SELECT ID_RECURSO FROM SEGT_RECURSOS WHERE RUTA_RECURSO='/payroll/employmentContract' AND ID_APLICACION =(SELECT ID_APLICACION FROM SEGT_APLICACIONES WHERE COD_APLICACION = 'GESTPYMESOC')));

INSERT INTO SEGT_DUAL VALUES('X');
